### ISSUE TITLE
data['ip'] is not being set in reporter.rb

### ISSUE THREAD

**Issue by akmalabbasov** [airbnb/optica#25]
HI, I'm using optica, where I have node1 which is running zookeeper, rabbitmq, optica and node2 which is configured to run chef-solo. I've put reporter handler to node2 so it can report run results. 
Everything is working, except `data['ip']` is not being set in `reporter.rb` which causes an invalid path in zookeeper when doing `settings.store.add(ip, data)`. I've changed it to `settings.store.add(data['hostname'], data)` and it's working fine.
Regarding `data['ip']` do I need to set it manually in `reporter.rb` by parsing `run_status`? And is it fine to leave it as `settings.store.add(data['hostname'], data)`.
Thank you.

**Comment by igor47** [comment]
hi, thanks for the ping. i've updated the `reporter.rb` script to the most recent version currently in use at airbnb. that should hopefully solve the issue you're encountering.
